[phases.setup]
nixPkgs = ["cairo", "pkg-config", "libjpeg", "zlib"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn flask_app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
